[build]
  command = "hugo mod get && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.135.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo mod get && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo mod get && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/open-positions"
  to = "/categories/open-positions/"
  status = 302
  
[[redirects]]
  from = "/meet"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_Mjc4MmI0MGItMjcxOC00OWQzLTliNWItZDlkNzlmNWVjOWRi%40thread.v2/0?context=%7b%22Tid%22%3a%228f7698bc-b1b4-439f-b259-0213401d1cfb%22%2c%22Oid%22%3a%22acee87ef-d88f-4dc1-a312-1e9893f75d96%22%7d"
  status = 302
  
[[redirects]]
  from = "/jhub"
  to = "https://jhub.sps-lab.org/"
  status = 302

[[redirects]]
  from = "/jhub-nordic"
  to = "https://jhub.sps-lab.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FSPS-L%2FNordic_JhubStart&urlpath=lab%2Ftree%2FNordic_JhubStart%2FExecute.ipynb&branch=main"
  status = 302
  
[[redirects]]
  from = "/jhub-sync-mach"
  to = "https://jhub.sps-lab.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FSPS-L%2FSync_mach_Octave&urlpath=lab%2Ftree%2FSync_mach_Octave%2F&branch=main"
  status = 302

[[redirects]]
  from = "/jhub-econ-oper"
  to = "https://jhub.sps-lab.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FSPS-L%2FEconomic-Operation-examples&urlpath=lab%2Ftree%2FEconomic-Operation-examples%2FED_example.ipynb&branch=main"
  status = 302 

[[redirects]]
  from = "/jhub-5-bus"
  to = "https://jhub.sps-lab.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FSPS-L%2F5_bus_test_system&urlpath=lab%2Ftree%2F5_bus_test_system%2FCase+2.ipynb&branch=main"
  status = 302 

[[redirects]]
  from = "/llm"
  to = "http://176.227.235.8:3000/"
  status = 302